[package]
name = "openxrlauncher-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.23.0"
# stereokit = { path = "../stereokit-rs" }
stereokit = "0.16.9"
libmonado-rs = { git = "https://github.com/technobaboo/libmonado-rs.git" }
svg = "0.14.0"
openxr = { version = "0.17.1", features = ["linked"] }
# stereokit-sys = { path = "../stereokit-sys" }
