[package]
name = "openxrlauncher-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "1.1.3"
dirs = "5.0.1"
egui = "0.24.1"
glam = "0.23.0"
home = "0.5.9"
open = "5.0.1"
regex = "1.10.2"
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
# stereokit = { path = "../stereokit-rs" }
stereokit = "0.16.8"
sysinfo = "0.30.2"
# libmonado-rs = { git = "https://github.com/technobaboo/libmonado-rs.git" }
